version: "3.5"
services:
  maven:
    image: ging/maven
    container_name: maven
    expose:
      - "8099"
    ports:
      - "8099:8099"
    environment:
      - "SPARK_MASTER=spark-masterspark-master-train:7077"
    volumes:
      - ./prediction-job:/prediction-job
    networks:
      - fiware
  
  # spark-master-train:
  #   image: bde2020/spark-master:2.4.5-hadoop2.7
  #   container_name: spark-master-train
  #   ports:
  #     - "8080:8080"
  #     - "7077:7077"
  #     - "9001:9001"
  #   environment:
  #     - INIT_DAEMON_STEP=setup_spark
  #     - "constraint:node==spark-master"
  #   networks:
  #     - fiware
  #   volumes:
  #     - ./prediction-job:/prediction-job

  # spark-worker-train:
  #   image: bde2020/spark-worker:2.4.5-hadoop2.7
  #   container_name: spark-worker-train
  #   depends_on:
  #     - spark-master-train
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - "SPARK_MASTER=spark://spark-master-train:7077"
  #     - "INIT_DAEMON_STEP=setup_spark"
  #     - "constraint:node==spark-worker"
  #     - "SERVER=proxy"
  #   networks:
  #     - fiware
  #   volumes:
  #     - ./prediction-job:/prediction-job

  spark-submit-train:
    build:
      context: ./docker
    container_name: spark-submit-train
    # depends_on:
    #   - spark-master
    #   - spark-worker-1
    ports:
      - "4040:4040"
    environment:
      - "SPARK_MASTER=spark://spark-master-train:7077"
      - "constraint:node==spark-submit"
      - "SERVER=proxy"
      - "MLFLOW_HOST=mlflow-server"
      - "CSV_FILE=carrefour_data_v0.csv"
    command: bash -c "sleep 15; sh /prediction-job/run-spark-jobs-train.sh"
    networks:
      - fiware
    volumes:
      - ./prediction-job:/prediction-job

  mlflow-server:
    image: ghcr.io/mlflow/mlflow:v1.30.0
    container_name: mlflow_server
    ports:
      - "5000:5000"
    command: mlflow server --host 0.0.0.0 --backend-store-uri sqlite:///prediction-job/mlflow/mlflow.db --default-artifact-root ./prediction-job/mlflow/artifacts 
    volumes:
      - ./prediction-job:/prediction-job
    networks:
      - fiware

networks:
  fiware:

